In [ ]:
import numpy as np 
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
data = np.loadtxt(open('/content/drive/MyDrive/Colab Notebooks/winequality-red.csv', "rb"), delimiter=";", skiprows=1)
print(data)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


2.	Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float

In [ ]:
wines=np.array(data)
print(wines)
print("data type",wines.dtype)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
data type float64


3.Shape of array


In [ ]:
print(wines.shape)

(1599, 12)


4.	Display the element at row 3 and column 4.

In [ ]:
print(wines[2,3])

2.3


5.	 Display the first three items from the fourth column.

In [ ]:
print(wines[:3,3])

[1.9 2.6 2.3]


6.	Display third column from each row.

In [ ]:
print(wines[:,2])

[0.   0.   0.04 ... 0.13 0.12 0.47]


7.	Display fourth row

In [ ]:
print(wines[3,:])

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


8.	Assign value 10 to 2nd row and 6th column element.

In [ ]:
wines[1,5]=10
print(wines[1,:])

[ 7.8     0.88    0.      2.6     0.098  10.     67.      0.9968  3.2
  0.68    9.8     5.    ]


9.	Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new.

In [ ]:
slice_new=wines[:,9]
slice_new=[666]*slice_new.size
print(slice_new)

[666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666, 666,

10.	Display wines array.

In [ ]:
print(wines[:,9])

[0.56 0.68 0.65 ... 0.75 0.71 0.66]


11.	Find the data type of wines array and Change the data type to int.

In [ ]:
print(wines.dtype)
wines_int=wines.astype(int)
print(wines_int.dtype)

float64
int64


12.	Add 10 points to each quality score.

In [ ]:
ad=wines[:,-1]+10
print(ad)

[15. 15. 15. ... 16. 15. 16.]


13.	Find the sum of all the elements in an array

In [ ]:
print(np.sum(wines))

152069.78194


14.	Find the sum of all the values in every column.

In [ ]:
print(np.sum(wines,axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25369.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


15.	Find the sum of all the values in every row.

In [ ]:
print(np.sum(wines,axis=1))

[ 74.5438  108.0548   99.699   ... 100.48174 105.21547  92.49249]


16.	Add the quality column to itself

In [ ]:
print(wines[:,-1]+wines[:,-1])

[10. 10. 10. ... 12. 10. 12.]


17.	Multiply alcohol by quality.

In [ ]:
print(wines[:,-1]*wines[:,-2])

[47. 49. 49. ... 66. 51. 66.]


18.	Display which wines have a quality rating higher than 5.

In [ ]:
print(wines[:,-1]>5)

[False False False ...  True False  True]


19.	Check if any wines have a quality rating equal to 10.

In [ ]:
print(wines[:,-1]==10)

[False False False ... False False False]


20.	Select rows in wines where the quality is over 7

In [ ]:
print(np.where(wines[:,-1]>7))

(array([ 267,  278,  390,  440,  455,  481,  495,  498,  588,  828, 1061,
       1090, 1120, 1202, 1269, 1403, 1449, 1549]),)


21.	Display wines with alcohol greater than 10 and quality greater than 7.

In [ ]:
print(np.where((wines[:,-2]>10) & (wines[:,-1]>7)))

(array([ 267,  278,  390,  455,  481,  495,  498,  588,  828, 1061, 1090,
       1120, 1202, 1269, 1449, 1549]),)


22.	Change the shape of wines array.

In [ ]:
print(wines.shape)
wines_shape=wines.flatten()
print(wines_shape)

#by using the reshape 
l=np.reshape(wines,-1)
print(l.shape)

(1599, 12)
[ 7.4   0.7   0.   ...  0.66 11.    6.  ]
(19188,)
